#
#    ██╗████████╗███████╗███╗░░░███╗░░░░░░░█████╗░░█████╗░░█████╗░██╗░░░░░██████╗░░█████╗░░██╗░░░░░░░██╗███╗░░██╗░██████╗
#    ██║╚══██╔══╝██╔════╝████╗░████║░░░░░░██╔══██╗██╔══██╗██╔══██╗██║░░░░░██╔══██╗██╔══██╗░██║░░██╗░░██║████╗░██║██╔════╝
#    ██║░░░██║░░░█████╗░░██╔████╔██║█████╗██║░░╚═╝██║░░██║██║░░██║██║░░░░░██║░░██║██║░░██║░╚██╗████╗██╔╝██╔██╗██║╚█████╗░
#    ██║░░░██║░░░██╔══╝░░██║╚██╔╝██║╚════╝██║░░██╗██║░░██║██║░░██║██║░░░░░██║░░██║██║░░██║░░████╔═████║░██║╚████║░╚═══██╗
#    ██║░░░██║░░░███████╗██║░╚═╝░██║░░░░░░╚█████╔╝╚█████╔╝╚█████╔╝███████╗██████╔╝╚█████╔╝░░╚██╔╝░╚██╔╝░██║░╚███║██████╔╝
#    ╚═╝░░░╚═╝░░░╚══════╝╚═╝░░░░░╚═╝░░░░░░░╚════╝░░╚════╝░░╚════╝░╚══════╝╚═════╝░░╚════╝░░░░╚═╝░░░╚═╝░░╚═╝░░╚══╝╚═════╝░
#
# Programmed by ItxItay and NAMD
# Contact us: https://github.com/ItxItayAndNotAMojangDev
#
# Items List: https://jd.papermc.io/paper/1.21.1/org/bukkit/Material.html
Item-CoolDowns:
  - "ENDER_EYE;30" #30 seconds